### PR TITLE
closes #9 closes #10:

### LINKED ISSUE #9: index.html skeleton

### LINKED ISSUE #10: Setup API Integration

### PR DESCRIPTION
**Pull request by adrianeyre**

### CODE REVIEW

**Comment by J-Marriott** [comment]
Been having a look through the code as a three, we think the API could do with being modularized and return the result to the caller (where it can be appended to the page using getElementIds) rather than document.write to the page.

http://stackoverflow.com/questions/802854/why-is-document-write-considered-a-bad-practice

**Comment by adrianeyre** [comment]
Thats the ticket we're working on now :-) to modularising and inserting into HTML tag. This ticket is just to read the API....it prints to the screen just for testing purposes

**Comment by adrianeyre** [comment]
document.write lines removed 👍

**Review by JamesTurnerGit — APPROVED** [review]
:shipit:

**Pull request merged**
